# Global variables
ARG DEBIAN_VERSION="13.3-slim" \
    DNSDIST_USER="dnsdist" \
    DNSDIST_VERSION="2.0.2" \
    IMAGE_VERSION="1.0.0"

# https://www.dnsdist.org/install.html#installing-from-source
# Set Debian as the base image
FROM debian:${DEBIAN_VERSION} AS dnsdist-build

# Build arguments
ARG ALPINE_VERSION \
    DEBIAN_FRONTEND="noninteractive" \
    DNSDIST_USER \
    DNSDIST_VERSION \
    DNSDIST_DOWNLOAD="https://downloads.powerdns.com/releases/dnsdist-${DNSDIST_VERSION}.tar.xz" \
    QUICHE_DOWNLOAD="https://github.com/cloudflare/quiche"

# Set shell for pipefail
SHELL ["/bin/bash", "-eo", "pipefail", "-c"]

# Install build dependencies
RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
      build-essential \
      pkgconf \
      cmake \
      meson \
      ninja-build \
      ca-certificates \
      curl \
      git \
      gpg \
      openssl \
      python3-yaml \
      clang \
      libboost-dev \
      liblua5.4-dev \
      libedit-dev \
      libevent-dev \
      libfstrm-dev \
      libbpf-dev \
      libxdp-dev \
      libcap-dev \
      libsodium-dev \
      libprotobuf-c-dev \
      libfontconfig-dev \
      liblmdb-dev \
      libssl-dev \
      libgnutls28-dev \
      libsnmp-dev \
      libnghttp2-dev \
      libre2-dev && \
    # Cleanup
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    # Install newest Rust and Cargo version (for quiche, DoQ and DoH3)
    curl --proto '=https' --tlsv1.3 -sSf https://sh.rustup.rs | sh -s -- -y
    # Add Rust to PATH
    # export PATH="$HOME/.cargo/bin:$PATH"

# Add Cargo/Rust to PATH
ENV PATH="/root/.cargo/bin:${PATH}"

# Set workdir
WORKDIR /tmp/quiche-build

# Download quiche for DoH3 and DoQ support
RUN git clone --recursive "${QUICHE_DOWNLOAD}" .

# Build quiche
RUN export RUSTFLAGS="-C target-feature=-crt-static" && \
    cargo build --release --package quiche --features ffi,pkg-config-meta

RUN mkdir -p /usr/local/include /usr/local/lib/pkgconfig && \
    cp -v quiche/include/quiche.h /usr/local/include/ && \
    # WICHTIG: Wir kopieren die .so Datei (Shared Lib)!
    cp -v target/release/deps/libquiche.so /usr/local/lib/ && \
    # Wir erstellen die .pc Datei neu, angepasst auf /usr/local
    printf "prefix=/usr/local\n\
exec_prefix=\${prefix}\n\
libdir=\${exec_prefix}/lib\n\
includedir=\${prefix}/include\n\
\n\
Name: quiche\n\
Description: QUIC transport protocol and HTTP/3 implementation\n\
Version: 0.24.5\n\
Libs: -L\${libdir} -lquiche\n\
Cflags: -I\${includedir}\n" > /usr/local/lib/pkgconfig/quiche.pc

# Set workdir
WORKDIR /tmp/dnsdist-build

# Download dnsdist source code and signature
RUN curl -sSLO "${DNSDIST_DOWNLOAD}" && \
    curl -sSLO "${DNSDIST_DOWNLOAD}.asc" && \
    # Import GPG keys for dnsdist verification
    gpg --keyserver keyserver.ubuntu.com --recv-keys 0xDCF513FA7EED19F3 0xA208ED4F8AF58446 0x6FFC33439B0D04DF 0xEACAB90B1963EC2B || true && \
    # Automatically trust the imported keys
    for fpr in $(gpg --list-keys --with-colons  | awk -F: '/fpr:/ {print $10}' | sort -u); do  echo -e "5\ny\n" |  gpg --command-fd 0 --expert --edit-key $fpr trust; done || true && \
    # Verify the downloaded dnsdist tarball with GPG
    gpg --verify "dnsdist-${DNSDIST_VERSION}.tar.xz.asc" "dnsdist-${DNSDIST_VERSION}.tar.xz" && \
    # Extract dnsdist source code
    tar -xf "dnsdist-${DNSDIST_VERSION}.tar.xz"

# Set workdir
WORKDIR /tmp/dnsdist-build/dnsdist-${DNSDIST_VERSION}

# Build DNSdist
RUN set -x && \
    # Set environment variables
    export PKG_CONFIG_PATH="/tmp/quiche-build/target/release:$PKG_CONFIG_PATH" && \
    export CFLAGS="-I/tmp/quiche-build/quiche/include" && \
    export CXXFLAGS="-I/tmp/quiche-build/quiche/include" && \
    export LDFLAGS="-L/tmp/quiche-build/target/release" && \
    # Configure dnsdist
    CC=clang CXX=clang++ \
    meson setup build \
      --prefix=/usr/local \
      --sysconfdir=/etc/dnsdist \
      -Ddns-over-quic=enabled \
      -Dquiche=enabled \
      -Ddns-over-http3=enabled \
      -Ddns-over-https=enabled \
      -Ddns-over-tls=enabled \
      -Dtls-gnutls=enabled \
      -Dtls-libssl=disabled \
      -Ddnstap=enabled \
      -Ddnscrypt=enabled \
      -Dyaml=enabled \
      -Dipcipher=enabled \
      -Dlibsodium=enabled \
      -Dlibedit=enabled \
      -Dre2=enabled \
      -Dxsk=enabled \
      -Dsnmp=enabled \
      -Dlibcap=enabled \
      -Dlua=lua5.4 \
      -Dnghttp2=enabled \
      -Dlmdb=enabled \
      -Db_lto=true \
      -Db_pie=true && \
    # Compile and install
    meson compile -C build && \
    meson install -C build

    # List options:
    # cat meson_options.txt
    # meson configure build

# Smoke test im Build Container
RUN dnsdist --version
